# Generated by Django 3.0.2 on 2020-01-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20200124_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostComments',
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
